# Generated by Django 4.2.1 on 2026-01-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('consumer_name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=500)),
                ('expiry_date', models.DateField()),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_status', models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid'), ('B', 'Blocked/Expired')], default='U', max_length=1)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kuickpay_consumers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consumer_number'], name='kuickpay_co_consume_142906_idx'), models.Index(fields=['bill_status'], name='kuickpay_co_bill_st_48c6f7_idx'), models.Index(fields=['expiry_date'], name='kuickpay_co_expiry__bca655_idx')],
            },
        ),
    ]
