# Generated by Django 6.0.1 on 2026-01-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_organization_discount_group'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumers', to='organization.organization'),
        ),
    ]
