# Generated by Django 4.2.1 on 2025-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_center', '0003_add_notes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncontact',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='promotioncontact',
            index=models.Index(fields=['email'], name='promotion_c_email_474212_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncontact',
            index=models.Index(fields=['contact_type'], name='promotion_c_contact_cc9821_idx'),
        ),
    ]
