# Generated by Django 4.2.1 on 2025-11-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_followup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='followup',
            new_name='leads_follo_status_d8909c_idx',
            old_name='leads_followup_status_idx',
        ),
        migrations.RenameIndex(
            model_name='followup',
            new_name='leads_follo_due_dat_f83679_idx',
            old_name='leads_followup_due_date_idx',
        ),
        migrations.AlterField(
            model_name='followup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups', to='leads.lead'),
        ),
    ]
