# Generated by manual edit
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_leads_followup_status_idx_leads_follo_status_d8909c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='loan_amount',
            field=models.DecimalField(default=0, max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recovered_amount',
            field=models.DecimalField(default=0, max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recovery_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='chat_messages',
            field=models.JSONField(null=True, blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_internal_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(null=True, blank=True),
        ),
    ]
