"""Add task_type field to Lead model.

Generated by assistant to persist `task_type` values passed in API requests.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_make_customer_name_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="task_type",
            field=models.CharField(max_length=64, null=True, blank=True),
        ),
    ]
