# Generated by Django 4.2.1 on 2025-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_assigned_to_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
