# Generated by Django 4.2.1 on 2025-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuphistory',
            name='contacted_via',
            field=models.CharField(choices=[('call', 'call'), ('whatsapp', 'whatsapp'), ('in-person', 'in-person'), ('cash', 'cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='followuphistory',
            name='followup_result',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('lost', 'lost'), ('loan_collection', 'loan_collection'), ('loan_cleared', 'loan_cleared'), ('loan_rescheduled', 'loan_rescheduled')], default='pending', max_length=20),
        ),
    ]
