# Generated by Django 4.2.1 on 2025-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_followuphistory_contacted_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_instant',
            field=models.BooleanField(default=False),
        ),
    ]
