# Generated by Django 4.2.1 on 2025-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_is_instant'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuphistory',
            name='is_instant',
            field=models.BooleanField(default=False),
        ),
    ]
