# Generated by Django 4.2.1 on 2025-11-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_rename_blog_formsubmissiontask_status_next_idx_blog_formsu_status_43e60a_idx_and_more'),
        ('leads', '0004_rename_leads_followup_status_idx_leads_follo_status_d8909c_idx_and_more'),
        ('organization', '0016_alter_employee_position_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_unique_id', models.CharField(db_index=True, help_text='Unique identifier for the form (auto-generated if not provided)', max_length=100, unique=True)),
                ('form_title', models.CharField(help_text='Title of the form', max_length=255)),
                ('is_linked_with_blog', models.BooleanField(default=False, help_text='If true, form appears below linked blog')),
                ('form_page_url', models.CharField(db_index=True, help_text='URL path for standalone form page (auto-generated from title if not provided)', max_length=255, unique=True)),
                ('display_position', models.CharField(choices=[('end_of_blog', 'End of Blog'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('standalone', 'Standalone Page')], default='end_of_blog', help_text='Where to display the form', max_length=50)),
                ('fields', models.JSONField(default=list, help_text='\n        Array of field objects. Each field should have:\n        {\n            "label": "Field Name",\n            "type": "text|textarea|dropdown|checkbox|radio|email|tel|number|date",\n            "placeholder": "Enter value",\n            "required": true|false,\n            "width": "full|half|third",\n            "options": ["option1", "option2"] (for dropdown/radio/checkbox)\n        }\n        ')),
                ('buttons', models.JSONField(default=list, help_text='\n        Array of button objects:\n        {\n            "label": "Submit",\n            "action": "submit|redirect|call",\n            "url": "optional URL for redirect/call actions",\n            "style": "primary|secondary|success|danger"\n        }\n        ')),
                ('notes', models.JSONField(default=list, help_text='\n        Array of note objects:\n        {\n            "text": "Note text (HTML allowed)",\n            "position": "above_field_name|below_field_name|above_submit_button|below_submit_button|top|bottom"\n        }\n        ')),
                ('form_header_image', models.CharField(blank=True, help_text='Optional header image URL', max_length=512, null=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for form styling', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata (analytics tracking, custom configs, etc.)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('submission_count', models.IntegerField(default=0, help_text='Total number of submissions received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional: Branch associated with this form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_forms', to='organization.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('linked_blog', models.ForeignKey(blank=True, help_text='Optional: Link this form to a specific blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='blog.blog')),
                ('organization', models.ForeignKey(db_constraint=False, help_text='Organization that owns this form', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_forms', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Dynamic Form',
                'verbose_name_plural': 'Dynamic Forms',
                'db_table': 'forms_dynamicform',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', models.JSONField(default=dict, help_text='Raw submission data from the form')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('referrer', models.CharField(blank=True, help_text='HTTP referrer URL', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.dynamicform')),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, help_text='Associated lead record created from this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'db_table': 'forms_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form', 'created_at'], name='forms_submi_form_id_7661c6_idx'), models.Index(fields=['lead'], name='forms_submi_lead_id_fc2dde_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dynamicform',
            index=models.Index(fields=['form_unique_id'], name='forms_dynam_form_un_69e69a_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicform',
            index=models.Index(fields=['status', 'created_at'], name='forms_dynam_status_635d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicform',
            index=models.Index(fields=['organization', 'status'], name='forms_dynam_organiz_d7f1df_idx'),
        ),
    ]
