# Generated by Django 4.2.1 on 2025-11-01 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0015_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('sales_executive', 'Sales Executive'), ('customer_service', 'Customer Service Representative'), ('accountant', 'Accountant'), ('operations', 'Operations Officer'), ('marketing', 'Marketing Executive'), ('ticketing_agent', 'Ticketing Agent'), ('travel_consultant', 'Travel Consultant'), ('supervisor', 'Supervisor'), ('assistant', 'Assistant'), ('other', 'Other')], help_text='Job title or position', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
