# Generated by Django 4.2.1 on 2025-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_employee_position_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('cancellation_policy', 'Cancellation Policy'), ('refund_policy', 'Refund Policy'), ('commission_policy', 'Commission Policy'), ('transport_policy', 'Transport Policy'), ('document_policy', 'Document Policy'), ('hotel_policy', 'Hotel Policy'), ('visa_policy', 'Visa Policy'), ('policy', 'Policy'), ('commission_rule', 'Commission Rule')], max_length=100),
        ),
    ]
