# Generated by Django 4.2.1 on 2025-11-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_rule_rule_type'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE organization_rule CHANGE COLUMN created_by_id created_by INT NULL;",
            reverse_sql="ALTER TABLE organization_rule CHANGE COLUMN created_by created_by_id INT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE organization_rule CHANGE COLUMN updated_by_id updated_by INT NULL;",
            reverse_sql="ALTER TABLE organization_rule CHANGE COLUMN updated_by updated_by_id INT NULL;"
        ),
    ]
