# Generated by Django 4.2.1 on 2026-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_add_resellrequest_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of credit currently used', max_digits=12),
        ),
    ]
