# Generated by Django 4.2.1 on 2026-01-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0100_add_payment_method_field'),
        ('organization', '0021_agency_credit_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='discount_group',
            field=models.ForeignKey(blank=True, help_text='Discount group assigned to this agency for automatic discount application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='booking.discountgroup'),
        ),
    ]
