# Generated by Django 4.2.1 on 2026-01-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_charges', '0002_hotelservicecharge_and_more'),
        ('organization', '0022_agency_discount_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='service_charge_group',
            field=models.ForeignKey(blank=True, help_text='Service charge group assigned to this branch for automatic charge application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='service_charges.servicechargerule'),
        ),
    ]
