# Generated by Django 4.2.1 on 2026-01-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_commissionrule_commission_and_more'),
        ('organization', '0024_employee_restructure_to_branch'),
    ]

    operations = [

        migrations.AddField(
            model_name='branch',
            name='commission_group',
            field=models.ForeignKey(blank=True, help_text='Commission group assigned to this branch for automatic commission calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_with_commission', to='commissions.commissionrule'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch'], name='organizatio_branch__cb0d7c_idx'),
        ),
    ]
