# Generated by Django 4.2.1 on 2026-01-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_remove_employee_organizatio_agency__5c21e8_idx_and_more'),
    ]

    operations = [
        # Index already removed or doesn't exist
    ]
