# Generated by Django 4.2.1 on 2026-01-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_remove_employee_organizatio_agency__5c21e8_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='organizatio_agency__5c21e8_idx',
        ),
    ]
