# Generated by Django 4.2.1 on 2026-01-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0109_remove_vehicletype_only_transport_charge_markuphotel'),
        ('organization', '0027_remove_employee_organizatio_agency__5c21e8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='markup_group',
            field=models.ForeignKey(blank=True, help_text='Markup group assigned to this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_organizations', to='booking.markup'),
        ),
    ]
