# Generated by Django 5.2.7 on 2025-11-02 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(db_index=True)),
                ('organization_id', models.IntegerField(db_index=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(db_index=True, max_length=30)),
                ('cnic', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('followup_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_lead',
            },
        ),
        migrations.CreateModel(
            name='FollowUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='passport_leads.passportlead')),
            ],
            options={
                'db_table': 'followup_log',
            },
        ),
        migrations.CreateModel(
            name='PaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_number', models.CharField(db_index=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pax', to='passport_leads.passportlead')),
            ],
            options={
                'db_table': 'pax_profile',
            },
        ),
        migrations.AddIndex(
            model_name='passportlead',
            index=models.Index(fields=['customer_phone'], name='passport_le_custome_880120_idx'),
        ),
        migrations.AddIndex(
            model_name='passportlead',
            index=models.Index(fields=['passport_number'], name='passport_le_passpor_f0ce3e_idx'),
        ),
        migrations.AddIndex(
            model_name='passportlead',
            index=models.Index(fields=['cnic'], name='passport_le_cnic_9232d3_idx'),
        ),
        migrations.AddIndex(
            model_name='passportlead',
            index=models.Index(fields=['branch_id'], name='passport_le_branch__cc9d78_idx'),
        ),
        migrations.AddIndex(
            model_name='passportlead',
            index=models.Index(fields=['next_followup_date'], name='passport_le_next_fo_4ed556_idx'),
        ),
        migrations.AddIndex(
            model_name='paxprofile',
            index=models.Index(fields=['passport_number'], name='pax_profile_passpor_13f05a_idx'),
        ),
    ]
