# Generated by Django 4.2.1 on 2025-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paxprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='issuing_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paxprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='paxprofile',
            index=models.Index(fields=['date_of_expiry'], name='pax_profile_date_of_6c29a6_idx'),
        ),
    ]
