# Generated by Django 4.2.1 on 2025-12-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_leads', '0002_paxprofile_address_paxprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paxprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
