# Generated by Django 4.2.1 on 2025-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_leads', '0003_paxprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportlead',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
