# Generated by Django 4.2.1 on 2025-12-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_passport_number'),
        ('passport_leads', '0004_passportlead_assigned_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportlead',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_leads', to='customers.customer'),
        ),
    ]
