# Generated by Django 4.2.1 on 2025-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_operationlog_and_housekeeping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roommap',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning_pending', 'Cleaning Pending'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='available', help_text='Current availability status of the room', max_length=20),
        ),
    ]
