# Generated by Django 4.2.1 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_missing_financialrecord_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('hotel_cleaning', 'Hotel Cleaning'), ('fuel', 'Fuel'), ('staff_salary', 'Staff Salary'), ('visa_fee', 'Visa Fee'), ('maintenance', 'Maintenance'), ('rent', 'Rent'), ('office_expense', 'Office Expense'), ('subscription', 'Subscription'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
