# Generated by Django 4.2.1 on 2025-11-01 12:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0074_change_ledger_id_to_foreign_key'),
        ('organization', '0016_alter_employee_position_alter_employee_user'),
        ('ledger', '0002_ledgerentry_internal_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AlterModelOptions(
            name='ledgerline',
            options={'ordering': ['created_at'], 'verbose_name': 'Ledger Line', 'verbose_name_plural': 'Ledger Lines'},
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='organization.agency'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Related booking if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='organization',
            field=models.ForeignKey(db_constraint=False, default=1, help_text='Organization owning this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reference_no',
            field=models.CharField(blank=True, db_index=True, help_text='Booking or invoice number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or reason', null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Account balance after this transaction', max_digits=18),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='booking_no',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who initiated this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='internal_notes',
            field=models.JSONField(blank=True, default=list, help_text='Audit trail and system notes'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data: amounts, customer info, etc.'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='narration',
            field=models.TextField(blank=True, help_text='Transaction description', null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reversed',
            field=models.BooleanField(default=False, help_text='True if this entry has been reversed'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reversed_of',
            field=models.ForeignKey(blank=True, help_text='Original entry that was reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='ledger.ledgerentry'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='service_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('umrah', 'Umrah'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('package', 'Package'), ('payment', 'Payment'), ('refund', 'Refund'), ('commission', 'Commission'), ('other', 'Other')], default='other', help_text='Service category for reporting', max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction_type',
            field=models.CharField(choices=[('booking_payment', 'Booking Payment'), ('refund', 'Refund'), ('commission', 'Commission'), ('manual_adjustment', 'Manual Adjustment'), ('payment_received', 'Payment Received'), ('balance_due', 'Balance Due')], default='booking_payment', help_text='Type of financial transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount credited (Liability/Income increases)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ledgerline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount debited (Asset/Expense increases)', max_digits=18),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference_no', 'organization'], name='ledger_ledg_referen_a4e366_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['booking_no', 'transaction_type'], name='ledger_ledg_booking_6df94a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['created_at'], name='ledger_ledg_created_b9f67d_idx'),
        ),
    ]
