# Generated by Django 4.2.1 on 2025-11-09 16:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_change_ledger_id_to_foreign_key'),
        ('area_leads', '0003_arealead_organization_id'),
        ('organization', '0016_alter_employee_position_alter_employee_user'),
        ('ledger', '0004_enhance_ledger_new_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='area_agency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Area agency if booking linked with area agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='area_leads.arealead'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='final_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calc from (total paid - total due)', max_digits=18),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='group_ticket_count',
            field=models.IntegerField(default=0, help_text='Total number of tickets if multiple in group booking'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='hotel_nights_count',
            field=models.IntegerField(default=0, help_text='Total hotel nights for all hotels in booking'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='inventory_owner_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Owner org of that inventory item (auto detect from item)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_ledger_entries', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payment_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of all linked payment record IDs'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='seller_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_ledger_entries', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction amount (kitna ki transaction howi hai)', max_digits=18),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='umrah_visa_count',
            field=models.IntegerField(default=0, help_text='Total number of Umrah visas included'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Agency if created by an agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='organization.agency'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='booking',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Related booking if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='booking_no',
            field=models.CharField(blank=True, db_index=True, help_text='Booking reference (auto from booking table)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Branch if created under branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Auto set (timezone aware)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='internal_notes',
            field=models.JSONField(blank=True, default=list, help_text='Array of timestamped notes like "[2025-10-17 11:24] Payment received via Bank Alfalah."'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='narration',
            field=models.TextField(blank=True, help_text='Text summary (e.g., "Advance payment for Umrah Booking #SK1234")', null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='service_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('umrah', 'Umrah'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('package', 'Package'), ('payment', 'Payment'), ('refund', 'Refund'), ('commission', 'Commission'), ('other', 'Other')], default='other', help_text='ticket / umrah / hotel / transport / package / payment / refund / commission', max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', help_text='debit or credit', max_length=50),
        ),
    ]
