# Generated by Django 4.2.1 on 2026-01-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_remove_employee_organizatio_agency__5c21e8_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0005_ledgerentry_area_agency_ledgerentry_final_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterOrgPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(help_text='Auto-generated: IOP-YYYYMMDD-XXXXX', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=15)),
                ('currency', models.CharField(default='PKR', help_text='Currency code', max_length=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('other', 'Other')], default='bank_transfer', max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Bank transaction ID, cheque number, etc.', max_length=100)),
                ('payment_date', models.DateField(help_text='Date when payment was made')),
                ('related_bookings', models.JSONField(blank=True, default=list, help_text='List of booking numbers this payment settles')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('attachment', models.FileField(blank=True, help_text='Payment proof (receipt, screenshot, etc.)', null=True, upload_to='interorg_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_interorg_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interorg_payments', to=settings.AUTH_USER_MODEL)),
                ('from_organization', models.ForeignKey(help_text='Reseller organization making the payment (e.g., Org 44)', on_delete=django.db.models.deletion.PROTECT, related_name='interorg_payments_made', to='organization.organization')),
                ('ledger_entry', models.ForeignKey(blank=True, help_text='Auto-created ledger entry for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interorg_payments', to='ledger.ledgerentry')),
                ('to_organization', models.ForeignKey(help_text='Owner organization receiving the payment (e.g., Org 11)', on_delete=django.db.models.deletion.PROTECT, related_name='interorg_payments_received', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Inter-Org Payment',
                'verbose_name_plural': 'Inter-Org Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_number'], name='ledger_inte_payment_d52bf8_idx'), models.Index(fields=['from_organization', 'to_organization'], name='ledger_inte_from_or_d717e5_idx'), models.Index(fields=['payment_date'], name='ledger_inte_payment_348f11_idx'), models.Index(fields=['status'], name='ledger_inte_status_35c859_idx')],
            },
        ),
    ]
