# Generated by Django 4.2.1 on 2026-01-24 14:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_interorgpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expense from purchase prices (cost of goods sold)', max_digits=18),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total income from selling prices (revenue)', max_digits=18),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit = Income - Expense', max_digits=18),
        ),
    ]
