# Generated by Django 4.2.1 on 2026-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_add_profit_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('RECEIVABLE', 'Receivable'), ('PAYABLE', 'Payable'), ('AGENT', 'Agent'), ('SALES', 'Sales'), ('COMMISSION', 'Commission'), ('SUSPENSE', 'Suspense'), ('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('EQUITY', 'Equity'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='service_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('umrah', 'Umrah'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('package', 'Package'), ('payment', 'Payment'), ('refund', 'Refund'), ('commission', 'Commission'), ('expense', 'Expense (Manual)'), ('income', 'Income (Manual)'), ('cash_transfer', 'Cash Transfer'), ('bank_transfer', 'Bank Transfer'), ('capital', 'Capital'), ('salary', 'Salary'), ('adjustment', 'Adjustment'), ('opening_balance', 'Opening Balance'), ('other', 'Other')], default='other', help_text='ticket / umrah / hotel / transport / package / payment / refund / commission', max_length=50),
        ),
    ]
