# Generated by Django 6.0.1 on 2026-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if this is a manual posting entry'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='locked',
            field=models.BooleanField(default=False, help_text='Locked entries cannot be edited/deleted, only reversed'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='ID of the referenced entity', null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reference_type',
            field=models.CharField(blank=True, help_text='Type of reference (e.g., vendor, employee, owner)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='service_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('umrah', 'Umrah'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('package', 'Package'), ('payment', 'Payment'), ('refund', 'Refund'), ('commission', 'Commission'), ('expense', 'Expense (Manual)'), ('income', 'Income (Manual)'), ('cash_transfer', 'Cash Transfer'), ('bank_transfer', 'Bank Transfer'), ('capital_in', 'Capital Injection'), ('capital_out', 'Capital Withdrawal'), ('salary', 'Salary Payment'), ('adjustment', 'Adjustment Entry'), ('opening_balance', 'Opening Balance'), ('ledger_adjustment', 'Ledger Adjustment'), ('credit_purchase', 'Credit Purchase'), ('vendor_payment', 'Vendor Payment'), ('vendor_advance', 'Vendor Advance'), ('advance_adjustment', 'Advance Adjustment'), ('bank_to_cash', 'Bank to Cash'), ('cash_to_bank', 'Cash to Bank'), ('other', 'Other')], default='other', help_text='ticket / umrah / hotel / transport / package / payment / refund / commission', max_length=50),
        ),
    ]
