# Generated by Django 6.0.1 on 2026-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_ledgerentry_is_manual_ledgerentry_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='For Bank Accounts only', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, help_text='For Bank Accounts only', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='iban',
            field=models.CharField(blank=True, help_text='For Bank Accounts only', max_length=100, null=True),
        ),
    ]
