# Generated by Django 5.2.7 on 2025-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_add_commission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationIDSequence',
            fields=[
                ('type_key', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('last_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
