# Generated by Django 5.2.7 on 2025-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_organizationidsequence_branch_branch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_code',
            field=models.CharField(blank=True, editable=False, help_text='Display code like AGN-0001', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, editable=False, help_text='Display code like BRN-0001', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(blank=True, editable=False, help_text='Display code like ORG-0001', max_length=20, null=True, unique=True),
        ),
    ]
