# Generated by Django 4.2.1 on 2025-11-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_rename_rule_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('hotel', 'Hotel'), ('ticket', 'Ticket'), ('package', 'Package')], max_length=20)),
                ('reseller', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resell_requests_received', to='organization.organization')),
                ('main_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resell_requests_sent', to='organization.organization')),
            ],
            options={
                'db_table': 'organization_resell_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
