# Generated by Django 4.2.1 on 2025-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_leads', '0002_alter_arealead_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealead',
            name='organization_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
