# Generated by Django 4.2.1 on 2025-11-01 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0016_alter_employee_position_alter_employee_user'),
        ('packages', '0032_alter_umrahvisapricetwohotel_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umrahpackage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Umrah Package', 'verbose_name_plural': 'Umrah Packages'},
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed package description', null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='end_date',
            field=models.DateField(blank=True, help_text='Package available till this date', null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Markup percentage on base price', max_digits=5),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='max_capacity',
            field=models.IntegerField(default=0, help_text='Total seats/slots available'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='package_code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='package_type',
            field=models.CharField(choices=[('umrah', 'Umrah Package'), ('visa', 'Visa Only'), ('package', 'Custom Package'), ('hotel', 'Hotel Only'), ('transport', 'Transport Only')], default='umrah', max_length=20),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='start_date',
            field=models.DateField(blank=True, help_text='Package available from this date', null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('sold_out', 'Sold Out')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible for public bookings'),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price per person', max_digits=12),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='reselling_allowed',
            field=models.BooleanField(default=False, help_text='Allow reselling by other organizations'),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='title',
            field=models.CharField(help_text="Package name (e.g., 'Ramzan Umrah Gold 2025')", max_length=200),
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('visa_type', models.CharField(choices=[('umrah', 'Umrah'), ('tourist', 'Tourist'), ('work', 'Work'), ('business', 'Business'), ('transit', 'Transit')], default='umrah', max_length=20)),
                ('country', models.CharField(choices=[('SAU', 'Saudi Arabia (KSA)'), ('UAE', 'United Arab Emirates'), ('QAT', 'Qatar'), ('OMN', 'Oman'), ('KWT', 'Kuwait'), ('BHR', 'Bahrain')], default='SAU', max_length=3)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('issued', 'Issued'), ('cancelled', 'Cancelled'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('infant_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('service_provider_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('validity_days', models.IntegerField(default=30, help_text='Visa validity in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Visa processing', '5-star hotel 5 nights'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in list')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.umrahpackage')),
            ],
            options={
                'verbose_name': 'Package Inclusion',
                'verbose_name_plural': 'Package Inclusions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Airfare', 'Personal expenses'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in list')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='packages.umrahpackage')),
            ],
            options={
                'verbose_name': 'Package Exclusion',
                'verbose_name_plural': 'Package Exclusions',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
