# Generated by Django 4.2.1 on 2025-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0033_alter_umrahpackage_options_umrahpackage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customumrahpackage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom Umrah Package', 'verbose_name_plural': 'Custom Umrah Packages'},
        ),
        migrations.AlterField(
            model_name='customumrahpackage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
