# Generated by Django 4.2.1 on 2025-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0034_alter_customumrahpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customumrahpackagehoteldetails',
            options={'verbose_name': 'Hotel Detail', 'verbose_name_plural': 'Hotel Details'},
        ),
        migrations.AlterField(
            model_name='customumrahpackagehoteldetails',
            name='room_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('executive', 'Executive'), ('presidential', 'Presidential'), ('family', 'Family Room'), ('economy', 'Economy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customumrahpackagehoteldetails',
            name='sharing_type',
            field=models.CharField(blank=True, choices=[('single', 'Single (1 Person)'), ('double', 'Double (2 Persons)'), ('triple', 'Triple (3 Persons)'), ('quad', 'Quad (4 Persons)'), ('quint', 'Quint (5 Persons)'), ('sharing', 'Sharing (Multiple)')], max_length=20, null=True),
        ),
    ]
