# Generated by Django 4.2.1 on 2025-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0036_alter_customumrahpackagetransportdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='double_bed_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='double_bed_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='quad_bed_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='quad_bed_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='quaint_bed_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='quaint_bed_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='sharing_bed_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='sharing_bed_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='triple_bed_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='triple_bed_selling_price',
            field=models.FloatField(default=0),
        ),
    ]
