# Generated by Django 4.2.1 on 2025-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0042_normalize_ziyarat_fields'),
    ]

    def ensure_columns(apps, schema_editor):
        # Add `purchase_price` column to foodprice and ziaratprice if missing.
        with schema_editor.connection.cursor() as c:
            try:
                c.execute("ALTER TABLE %s ADD COLUMN purchase_price DOUBLE DEFAULT 0" % schema_editor.quote_name('packages_foodprice'))
            except Exception:
                # Column probably exists already
                pass
            try:
                c.execute("ALTER TABLE %s ADD COLUMN purchase_price DOUBLE DEFAULT 0" % schema_editor.quote_name('packages_ziaratprice'))
            except Exception:
                pass

    operations = [
        migrations.RunPython(ensure_columns, reverse_code=migrations.RunPython.noop),
    ]
