# Generated by Django 4.2.1 on 2025-11-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0043_foodprice_purchase_price_ziaratprice_purchase_price'),
    ]

    def ensure_columns(apps, schema_editor):
        # Add transport_selling_price and transport_purchase_price columns
        # to transport detail tables if they don't already exist. Use
        # raw ALTER TABLE to be robust against partially-applied schema.
        with schema_editor.connection.cursor() as c:
            try:
                c.execute("ALTER TABLE %s ADD COLUMN transport_purchase_price DOUBLE DEFAULT 0" % schema_editor.quote_name('packages_customumrahpackagetransportdetails'))
            except Exception:
                pass
            try:
                c.execute("ALTER TABLE %s ADD COLUMN transport_selling_price DOUBLE DEFAULT 0" % schema_editor.quote_name('packages_customumrahpackagetransportdetails'))
            except Exception:
                pass
            try:
                c.execute("ALTER TABLE %s ADD COLUMN transport_purchase_price DOUBLE DEFAULT 0" % schema_editor.quote_name('packages_umrahpackagetransportdetails'))
            except Exception:
                pass
            try:
                c.execute("ALTER TABLE %s ADD COLUMN transport_selling_price DOUBLE DEFAULT 0" % schema_editor.quote_name('packages_umrahpackagetransportdetails'))
            except Exception:
                pass

    operations = [
        migrations.RunPython(ensure_columns, reverse_code=migrations.RunPython.noop),
    ]
