# Generated by Django 4.2.1 on 2025-11-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0045_ensure_transport_price_columns'),
    ]

    def ensure_drop_columns(apps, schema_editor):
        cols = [
            'adault_visa_price',
            'child_visa_price',
            'food_price',
            'infant_visa_price',
            'madinah_ziarat_purchase_price',
            'madinah_ziyarat_price',
            'makkah_ziarat_purchase_price',
            'makkah_ziyarat_price',
            'transport_price',
        ]
        table = schema_editor.quote_name('packages_umrahpackage')
        with schema_editor.connection.cursor() as c:
            for col in cols:
                try:
                    c.execute(f"ALTER TABLE {table} DROP COLUMN {schema_editor.quote_name(col)}")
                except Exception:
                    # ignore if column doesn't exist or other DB-specific errors
                    pass

    operations = [
        migrations.RunPython(ensure_drop_columns, reverse_code=migrations.RunPython.noop),
    ]
