# Generated by Django 4.2.1 on 2025-11-19 23:14

from django.db import migrations, models


def drop_legacy_columns(apps, schema_editor):
    """Safely drop legacy columns if they exist (works across DBs).

    This checks information_schema for MySQL and uses a conditional drop
    to avoid failing when columns were already removed.
    """
    table = 'packages_umrahpackage'
    legacy_columns = [
        'adault_visa_price', 'child_visa_price', 'food_price', 'infant_visa_price',
        'madinah_ziarat_purchase_price', 'madinah_ziyarat_price',
        'makkah_ziarat_purchase_price', 'makkah_ziyarat_price', 'transport_price',
    ]

    conn = schema_editor.connection
    with conn.cursor() as cursor:
        for col in legacy_columns:
            try:
                # Check existence via information_schema for MySQL/Postgres
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM information_schema.COLUMNS
                    WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s
                    """,
                    (table, col),
                )
                row = cursor.fetchone()
                exists = row and row[0] > 0
            except Exception:
                # Fallback: try generic approach (this may error on some DBs)
                exists = False

            if exists:
                try:
                    cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{col}`")
                except Exception:
                    # If DROP fails for some DB-specific reason, ignore to allow
                    # migrations to continue — the column may be managed elsewhere.
                    pass


def add_transport_columns(apps, schema_editor):
    """Add transport_selling_price & transport_purchase_price columns if missing."""
    tables = [
        'packages_customumrahpackagetransportdetails',
        'packages_umrahpackagetransportdetails',
    ]
    columns = [
        ('transport_purchase_price', 'FLOAT DEFAULT 0'),
        ('transport_selling_price', 'FLOAT DEFAULT 0'),
    ]

    conn = schema_editor.connection
    with conn.cursor() as cursor:
        for table in tables:
            for colname, coldef in columns:
                try:
                    cursor.execute(
                        """
                        SELECT COUNT(*) FROM information_schema.COLUMNS
                        WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s
                        """,
                        (table, colname),
                    )
                    row = cursor.fetchone()
                    exists = row and row[0] > 0
                except Exception:
                    exists = False

                if not exists:
                    try:
                        cursor.execute(f"ALTER TABLE `{table}` ADD COLUMN `{colname}` {coldef}")
                    except Exception:
                        # ignore individual add failures to allow migration to proceed
                        pass


def add_purchase_price_columns(apps, schema_editor):
    """Add purchase_price column to foodprice and ziaratprice if missing."""
    targets = [
        ('packages_foodprice', 'purchase_price'),
        ('packages_ziaratprice', 'purchase_price'),
    ]
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        for table, colname in targets:
            try:
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM information_schema.COLUMNS
                    WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s
                    """,
                    (table, colname),
                )
                row = cursor.fetchone()
                exists = row and row[0] > 0
            except Exception:
                exists = False

            if not exists:
                try:
                    cursor.execute(f"ALTER TABLE `{table}` ADD COLUMN `{colname}` FLOAT DEFAULT 0")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0047_rename_markup_to_profit_and_remove_tax'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_columns, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_transport_columns, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_purchase_price_columns, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='umrahpackage',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit percentage on base price', max_digits=5),
        ),
    ]
