# Generated by Django 4.2.1 on 2025-11-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0049_add_selected_option_ids'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
