# Generated by Django 4.2.1 on 2025-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0050_remove_umrahpackage_adault_visa_price_and_more'),
    ]

    operations = [
        # Use a Python migration to drop each column only if it exists.
        migrations.RunPython(
            code=lambda apps, schema_editor: _drop_umrahpackage_columns(schema_editor),
            reverse_code=lambda apps, schema_editor: None,
        ),
        # Add new price columns only if they don't already exist in the DB.
        migrations.RunPython(
            code=lambda apps, schema_editor: _add_price_columns(schema_editor),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]


def _drop_umrahpackage_columns(schema_editor):
    cols = [
        'adault_visa_price', 'child_visa_price', 'food_price', 'infant_visa_price',
        'madinah_ziarat_purchase_price', 'madinah_ziyarat_price',
        'makkah_ziarat_purchase_price', 'makkah_ziyarat_price', 'transport_price',
    ]
    table = 'packages_umrahpackage'
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SELECT DATABASE()')
            dbname = cursor.fetchone()[0]
    except Exception:
        dbname = None

    for col in cols:
        try:
            with schema_editor.connection.cursor() as cursor:
                if dbname:
                    cursor.execute(
                        "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=%s AND TABLE_NAME=%s AND COLUMN_NAME=%s",
                        (dbname, table, col),
                    )
                else:
                    cursor.execute(
                        "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_NAME=%s AND COLUMN_NAME=%s",
                        (table, col),
                    )
                exists = cursor.fetchone()[0] > 0
                if exists:
                    cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{col}`")
        except Exception:
            continue


def _add_price_columns(schema_editor):
    # [(table, column, sql_type_and_default), ...]
    additions = [
        ('packages_customumrahpackagetransportdetails', 'transport_purchase_price', 'DOUBLE NOT NULL DEFAULT 0'),
        ('packages_customumrahpackagetransportdetails', 'transport_selling_price', 'DOUBLE NOT NULL DEFAULT 0'),
        ('packages_foodprice', 'purchase_price', 'DOUBLE NOT NULL DEFAULT 0'),
        ('packages_umrahpackagetransportdetails', 'transport_purchase_price', 'DOUBLE NOT NULL DEFAULT 0'),
        ('packages_umrahpackagetransportdetails', 'transport_selling_price', 'DOUBLE NOT NULL DEFAULT 0'),
        ('packages_ziaratprice', 'purchase_price', 'DOUBLE NOT NULL DEFAULT 0'),
    ]
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SELECT DATABASE()')
            dbname = cursor.fetchone()[0]
    except Exception:
        dbname = None

    for table, col, col_def in additions:
        try:
            with schema_editor.connection.cursor() as cursor:
                if dbname:
                    cursor.execute(
                        "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=%s AND TABLE_NAME=%s AND COLUMN_NAME=%s",
                        (dbname, table, col),
                    )
                else:
                    cursor.execute(
                        "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_NAME=%s AND COLUMN_NAME=%s",
                        (table, col),
                    )
                exists = cursor.fetchone()[0] > 0
                if not exists:
                    cursor.execute(f"ALTER TABLE `{table}` ADD COLUMN `{col}` {col_def}")
        except Exception:
            # ignore failing adds and continue
            continue
