# Generated by Django 4.2.1 on 2025-11-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0051_remove_umrahpackage_adault_visa_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umrahvisapricetwo',
            old_name='adault_price',
            new_name='adult_purchase_price',
        ),
        migrations.RenameField(
            model_name='umrahvisapricetwo',
            old_name='child_price',
            new_name='adult_selling_price',
        ),
        migrations.RenameField(
            model_name='umrahvisapricetwo',
            old_name='infant_price',
            new_name='child_purchase_price',
        ),
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='child_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='infant_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='infant_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='UmrahVisaPriceTwoHotel',
        ),
    ]
