# Generated by assistant to add per-person price fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0052_rename_adault_price_umrahvisapricetwo_adult_purchase_price_and_more'),
    ]

    operations = [
        # OnlyVisaPrice per-person fields
        migrations.AddField(
            model_name='onlyvisaprice',
            name='adult_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='adult_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='child_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='child_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='infant_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='infant_purchase_price',
            field=models.FloatField(default=0),
        ),

        # TransportSectorPrice per-person fields
        migrations.AddField(
            model_name='transportsectorprice',
            name='adult_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='adult_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='child_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='child_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='infant_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='infant_purchase_price',
            field=models.FloatField(default=0),
        ),

        # FoodPrice per-person fields
        migrations.AddField(
            model_name='foodprice',
            name='adult_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='adult_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='child_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='child_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='infant_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='infant_purchase_price',
            field=models.FloatField(default=0),
        ),

        # ZiaratPrice per-person fields
        migrations.AddField(
            model_name='ziaratprice',
            name='adult_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='adult_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='child_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='child_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='infant_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='infant_purchase_price',
            field=models.FloatField(default=0),
        ),
    ]
