# Generated by Django 4.2.1 on 2025-12-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0052_add_transportsectorprice_personal_price_fields'),
        ('packages', '0057_add_food_ziarat_per_person_fields'),
    ]

    operations = [
    ]
