# Generated by Django 4.2.1 on 2025-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0058_merge_20251206_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahpackage',
            name='adault_visa_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='child_visa_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='food_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='infant_visa_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='madinah_ziarat_purchase_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='madinah_ziyarat_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='makkah_ziarat_purchase_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='makkah_ziyarat_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='transport_price',
        ),
        migrations.AddField(
            model_name='customumrahpackagetransportdetails',
            name='transport_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customumrahpackagetransportdetails',
            name='transport_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagetransportdetails',
            name='transport_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagetransportdetails',
            name='transport_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='onlyvisaprice',
            name='long_term_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discount percentage for long-term visas', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='onlyvisaprice',
            name='multi_entry',
            field=models.BooleanField(default=False, help_text='Whether this visa supports multiple entry (long-term)'),
        ),
        migrations.AlterField(
            model_name='onlyvisaprice',
            name='validity_days',
            field=models.IntegerField(blank=True, help_text='Optional validity/duration in days for long term visas', null=True),
        ),
    ]
