# Generated by Django 4.2.1 on 2026-01-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0059_remove_umrahpackage_adault_visa_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingexpiry',
            name='custom_umrah_expiry_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingexpiry',
            name='customer_expiry_time',
            field=models.IntegerField(default=0),
        ),
    ]
