# Generated by Django 4.2.1 on 2026-01-24 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0106_vehicletype_only_transport_charge'),
        ('packages', '0060_bookingexpiry_custom_umrah_expiry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportsectorprice',
            name='adult_purchase_price',
        ),
        migrations.RemoveField(
            model_name='transportsectorprice',
            name='adult_selling_price',
        ),
        migrations.RemoveField(
            model_name='transportsectorprice',
            name='child_purchase_price',
        ),
        migrations.RemoveField(
            model_name='transportsectorprice',
            name='child_selling_price',
        ),
        migrations.RemoveField(
            model_name='transportsectorprice',
            name='infant_purchase_price',
        ),
        migrations.RemoveField(
            model_name='transportsectorprice',
            name='infant_selling_price',
        ),
        migrations.AlterField(
            model_name='umrahpackagetransportdetails',
            name='transport_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.vehicletype'),
        ),
    ]
