# Generated by Django 4.2.1 on 2026-01-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0061_remove_transportsectorprice_adult_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='double_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='double_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='quad_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='quad_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='quaint_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='quaint_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='sharing_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='sharing_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='triple_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='triple_selling_price',
            field=models.FloatField(default=0),
        ),
    ]
