# Generated by Django 4.2.1 on 2026-01-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0062_umrahpackage_double_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='child_package_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_package_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='infant_package_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='infant_package_selling_price',
            field=models.FloatField(default=0),
        ),
    ]
