# Generated by Django 4.2.1 on 2026-01-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0063_umrahpackage_child_package_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umrahpackage',
            old_name='child_package_purchase_price',
            new_name='child_double_purchase_price',
        ),
        migrations.RenameField(
            model_name='umrahpackage',
            old_name='child_package_selling_price',
            new_name='child_double_selling_price',
        ),
        migrations.RenameField(
            model_name='umrahpackage',
            old_name='quaint_purchase_price',
            new_name='child_quad_purchase_price',
        ),
        migrations.RenameField(
            model_name='umrahpackage',
            old_name='quaint_selling_price',
            new_name='child_quad_selling_price',
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_quaint_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_quaint_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_sharing_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_sharing_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_triple_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_triple_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_without_bed_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_without_bed_selling_price',
            field=models.FloatField(default=0),
        ),
    ]
