# Generated by Django 4.2.1 on 2026-01-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0064_rename_child_package_purchase_price_umrahpackage_child_double_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='quaint_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='quaint_selling_price',
            field=models.FloatField(default=0),
        ),
    ]
