# Generated by Django 4.2.1 on 2025-12-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_add_resellrequest_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_remove_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Early checkout approval'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Expected check-in time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Expected check-out time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='grace_minutes',
            field=models.IntegerField(default=0, help_text='Grace period for late check-in (minutes)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_contact_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_account_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_payment_date',
            field=models.IntegerField(blank=True, help_text='Day of month (1-31) for salary payment', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('grace', 'Grace Period'), ('late', 'Late'), ('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('early_checkout', 'Early Checkout'), ('full_day', 'Full Day Leave'), ('partial_day', 'Partial Day Leave')], max_length=20)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('applied_to_salary_month', models.DateField(blank=True, help_text='Month/year when fine was deducted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='hr.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.commissiongroup'),
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fine_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Base + Commission - Fines', max_digits=12)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='hr.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
