# Generated by Django 4.2.1 on 2025-12-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_commissiongroup_attendance_approval_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='actual_payment_date',
            field=models.DateField(blank=True, help_text='Date when salary was actually paid', null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='days_late',
            field=models.IntegerField(default=0, help_text='Number of days payment was delayed'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='expected_payment_date',
            field=models.DateField(blank=True, help_text='Date when salary should be paid', null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Whether payment was made after expected date'),
        ),
    ]
