# Generated by Django 4.2.1 on 2025-12-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_commissionrule_commission_and_more'),
        ('hr', '0005_salarypayment_actual_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employees', to='commissions.commissionrule'),
        ),
    ]
