# Generated by Django 4.2.1 on 2026-01-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_commission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='service_type',
            field=models.CharField(blank=True, help_text='Type of service (e.g. group_ticket, umrah_package)', max_length=50, null=True),
        ),
    ]
