# Generated by Django 4.2.1 on 2025-11-01 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_ticket_options_ticket_adult_fare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0036_alter_customumrahpackagetransportdetails_options_and_more'),
        ('booking', '0072_bookingpersondetail_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ledger_id',
            field=models.IntegerField(blank=True, help_text='Link to ledger entry', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BookingStatusTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_timeline', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Booking Status Timeline',
                'verbose_name_plural': 'Booking Status Timelines',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BookingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion_name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('per_item', 'Per Item')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('applies_to', models.CharField(choices=[('total', 'Total Amount'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('visa', 'Visa'), ('package', 'Package')], default='total', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promotions', to='booking.booking')),
                ('discount_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_applications', to='booking.discountgroup')),
            ],
            options={
                'verbose_name': 'Booking Promotion',
                'verbose_name_plural': 'Booking Promotions',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_entry_id', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_entries', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pax_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_pax', to='booking.booking')),
                ('person_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pax_records', to='booking.bookingpersondetail')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pax', to='packages.visa')),
            ],
            options={
                'verbose_name': 'Booking PAX',
                'verbose_name_plural': 'Booking PAX',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('hotel', 'Hotel'), ('transport', 'Transport'), ('package', 'Package'), ('visa', 'Visa'), ('ticket', 'Ticket'), ('ziyarat', 'Ziyarat'), ('food', 'Food'), ('other', 'Other')], max_length=20)),
                ('item_name', models.CharField(help_text='Display name for the item', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_details', models.JSONField(blank=True, default=dict, help_text='Store type-specific details like room_type, check_in, vehicle_type, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='booking.booking')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='tickets.hotels')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_booking_items', to='packages.umrahpackage')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='tickets.ticket')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='packages.transportsectorprice')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='packages.visa')),
            ],
            options={
                'verbose_name': 'Booking Item',
                'verbose_name_plural': 'Booking Items',
                'ordering': ['id'],
            },
        ),
    ]
