# Generated by Django 4.2.1 on 2025-11-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgerentry_internal_notes'),
        ('booking', '0073_booking_customer_address_booking_customer_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ledger_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, help_text='Auto-created ledger entry when booking is paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='ledger.ledgerentry'),
        ),
    ]
