# Generated by Django 4.2.1 on 2025-11-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_bankaccount_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='agent_bank',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='organization_bank',
        ),
        migrations.AddField(
            model_name='payment',
            name='agent_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_payments', to='booking.bankaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_payments', to='booking.bankaccount'),
        ),
    ]
