# Generated by Django 4.2.1 on 2025-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0078_add_allowed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_depositor_cnic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_depositor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
