# Generated by Django 4.2.1 on 2025-11-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_payment_bank_name_payment_cash_depositor_cnic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
    ]
