# Generated by Django 4.2.1 on 2025-11-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0080_remove_payment_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRNSequence',
            fields=[
                ('prefix', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_seq', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'booking_trnsequence',
            },
        ),
    ]
