# Generated by Django 4.2.1 on 2025-11-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_add_per_person_price_fields'),
        ('booking', '0081_trnsequence'),
    ]

    operations = [
    ]
