# Generated by Django 4.2.1 on 2025-11-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0082_merge_20251125_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
