# Generated by Django 4.2.1 on 2025-12-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0082_add_vehicletype_personal_price_fields'),
        ('booking', '0084_add_sector_type_fields'),
    ]

    operations = [
    ]
