# Generated by Django 4.2.1 on 2025-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0085_merge_20251206_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Un-approved', 'Un-approved'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Under-process', 'Under-process'), ('Approved', 'Approved'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
