# Generated by Django 4.2.1 on 2025-12-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0086_remove_payment_status_add_new_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='visa_rate',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='visa_rate_in_pkr',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='visa_riyal_rate',
        ),
    ]
