# Generated by Django 4.2.1 on 2025-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0087_remove_bookingpersondetail_visa_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_rate_in_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
