# Generated by Django 4.2.1 on 2025-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0088_bookingpersondetail_visa_rate_in_pkr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_riyal_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
