# Generated by Django 4.2.1 on 2025-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0089_bookingpersondetail_visa_riyal_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransportsector',
            name='is_airport_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingtransportsector',
            name='is_airport_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingtransportsector',
            name='is_hotel_to_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingtransportsector',
            name='sector_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
