# Generated by Django 4.2.1 on 2025-12-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0090_bookingtransportsector_is_airport_drop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingZiyaratDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziarat', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('adult_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('total_adults', models.IntegerField(default=0)),
                ('total_children', models.IntegerField(default=0)),
                ('total_infants', models.IntegerField(default=0)),
                ('is_price_pkr', models.BooleanField(default=False)),
                ('riyal_rate', models.FloatField(default=0)),
                ('total_price_pkr', models.FloatField(default=0)),
                ('total_price_sar', models.FloatField(default=0)),
                ('inventory_owner_organization_id', models.IntegerField(blank=True, null=True)),
                ('booking_organization_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ziyarat_voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ziyarat_brn', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarat_details', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingFoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('adult_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('total_adults', models.IntegerField(default=0)),
                ('total_children', models.IntegerField(default=0)),
                ('total_infants', models.IntegerField(default=0)),
                ('is_price_pkr', models.BooleanField(default=False)),
                ('riyal_rate', models.FloatField(default=0)),
                ('total_price_pkr', models.FloatField(default=0)),
                ('total_price_sar', models.FloatField(default=0)),
                ('inventory_owner_organization_id', models.IntegerField(blank=True, null=True)),
                ('booking_organization_id', models.IntegerField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('food_voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('food_brn', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='booking.booking')),
            ],
        ),
    ]
