# Generated by Django 4.2.1 on 2025-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0091_bookingziyaratdetails_bookingfooddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='booking_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='inventory_owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='booking_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='inventory_owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='booking_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='inventory_owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtransportdetails',
            name='brn_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtransportdetails',
            name='price_in_sar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtransportdetails',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
