# Generated by Django 4.2.1 on 2025-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0092_bookinghoteldetails_booking_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransportsector',
            name='big_sector_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
