# Generated by Django 4.2.1 on 2025-12-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0093_bookingtransportsector_big_sector_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtransportsector',
            name='big_sector_id',
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='big_sector_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransportsector',
            name='arrival_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransportsector',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
