# Generated by Django 4.2.1 on 2025-12-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0094_remove_bookingtransportsector_big_sector_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtransportdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookingtransportdetails',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='bookingtransportdetails',
            name='price_in_sar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingtransportdetails',
            name='riyal_rate',
            field=models.FloatField(default=50),
        ),
    ]
