# Generated by Django 4.2.1 on 2025-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0095_remove_bookingtransportdetails_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_information',
            field=models.JSONField(blank=True, default=list, help_text='Array of contact objects with name, email, phone', null=True),
        ),
    ]
