# Generated by Django 4.2.1 on 2025-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0095_remove_bookingtransportdetails_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfooddetails',
            name='status',
            field=models.CharField(default='Served', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingziyaratdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
