# Generated by Django 4.2.1 on 2025-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0096_bookingfooddetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='food_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='hotel_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='transport_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ziyarat_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
