# Generated by Django 4.2.1 on 2025-12-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking', '0097_bookingpersondetail_food_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_status_records', to='booking.bookingpersondetail')),
            ],
            options={
                'verbose_name': 'Passenger Activity Status',
                'verbose_name_plural': 'Passenger Activity Statuses',
                'unique_together': {('passenger', 'content_type', 'object_id')},
            },
        ),
    ]
