# Generated by Django 4.2.1 on 2025-12-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0096_booking_contact_information'),
        ('booking', '0098_passengeractivitystatus'),
    ]

    operations = [
    ]
