# Generated by Django 4.2.1 on 2026-01-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0100_add_payment_method_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_group',
            field=models.ForeignKey(blank=True, help_text='Discount group that was applied to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.discountgroup'),
        ),
    ]
