# Generated by Django 4.2.1 on 2026-01-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_merge_20251228_1828'),
        ('booking', '0101_booking_discount_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingticketdetails',
            name='departure_stay_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingticketdetails',
            name='return_stay_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingticketdetails',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='bookingticketdetails',
            name='trip_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
