# Generated by Django 4.2.1 on 2026-01-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_merge_20251228_1828'),
        ('booking', '0102_alter_bookingticketdetails_departure_stay_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingticketdetails',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket'),
        ),
    ]
