# Generated by Django 4.2.1 on 2026-01-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0102_alter_bookingticketdetails_departure_stay_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassengerActivityStatus',
        ),
    ]
