# Generated by Django 4.2.1 on 2026-01-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0103_alter_bookingticketdetails_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='airline_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='arrival_city_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='departure_city_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
