# Generated by Django 4.2.1 on 2026-01-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_employee_restructure_to_branch'),
        ('booking', '0104_bookingtickettickettripdetails_airline_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee who made this booking (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='organization.agency'),
        ),
    ]
