# Generated by Django 4.2.1 on 2026-01-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0105_booking_employee_alter_booking_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingticketdetails',
            name='adult_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='adult_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='child_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='child_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='infant_purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='infant_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
