# Generated by Django 4.2.1 on 2026-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0105_booking_employee_alter_booking_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='only_transport_charge',
            field=models.BooleanField(default=False),
        ),
    ]
