# Generated by Django 4.2.1 on 2026-01-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0106_bookingticketdetails_adult_purchase_price_and_more'),
        ('booking', '0106_vehicletype_only_transport_charge'),
    ]

    operations = [
    ]
