# Generated by Django 4.2.1 on 2026-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0107_merge_20260125_0705'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='markup',
            name='applies_to',
            field=models.CharField(default='group_ticket', max_length=100),
        ),
    ]
