# Generated by Django 4.2.1 on 2026-01-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_ticket_history'),
        ('booking', '0108_remove_vehicletype_only_transport_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='only_transport_charge',
        ),
        migrations.CreateModel(
            name='MarkupHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quint', models.FloatField(default=0)),
                ('quad', models.FloatField(default=0)),
                ('triple', models.FloatField(default=0)),
                ('double', models.FloatField(default=0)),
                ('sharing', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.hotels')),
                ('markup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_markups', to='booking.markup')),
            ],
        ),
    ]
