# Generated by Django 4.2.1 on 2026-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0109_remove_vehicletype_only_transport_charge_markuphotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='assigned_families',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
