# Generated by Django 4.2.1 on 2026-01-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0110_bookinghoteldetails_assigned_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_details', to='booking.sector'),
        ),
    ]
