# Generated by Django 4.2.1 on 2026-01-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0065_umrahpackage_quaint_purchase_price_and_more'),
        ('booking', '0111_bookingtransportdetails_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfooddetails',
            name='food_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_food_details', to='packages.foodprice'),
        ),
        migrations.AddField(
            model_name='bookingziyaratdetails',
            name='ziarat_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_ziyarat_details', to='packages.ziaratprice'),
        ),
    ]
