# Generated by Django 4.2.1 on 2026-01-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0112_bookingfooddetails_food_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='voucher_status',
            field=models.CharField(blank=True, default='Draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
