# Generated by Django 4.2.1 on 2025-11-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_formsubmissiontask_status_next_idx_blog_formsu_status_43e60a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='blog/covers/'),
        ),
    ]
