# Generated by Django 4.2.1 on 2025-11-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='author_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
