# Generated by Django 4.2.1 on 2025-11-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='author_email',
        ),
    ]
