# Generated by Django 4.2.1 on 2026-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogcomment_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='custom_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='section_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
