# Generated by Django 4.2.1 on 2026-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_custom_styles_blog_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadform',
            name='display_position',
            field=models.CharField(choices=[('end_of_blog', 'End of Blog'), ('sidebar', 'Sidebar'), ('popup', 'Popup Modal'), ('standalone', 'Standalone Page')], default='end_of_blog', max_length=50),
        ),
        migrations.AddField(
            model_name='leadform',
            name='is_linked_with_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadform',
            name='linked_blog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
