# Generated by Django 4.2.1 on 2026-01-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('booking_ref_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(default='HK', max_length=10)),
                ('airline_locator', models.CharField(blank=True, max_length=50, null=True)),
                ('airline_code', models.CharField(blank=True, max_length=10, null=True)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('origin_city', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cabin_class', models.CharField(default='Economy', max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('segments', models.JSONField(blank=True, null=True)),
                ('supplier_code', models.IntegerField(blank=True, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flight_bookings',
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['pnr'], name='flight_book_pnr_ac7963_idx'), models.Index(fields=['booking_ref_id'], name='flight_book_booking_591d21_idx'), models.Index(fields=['user', '-booking_date'], name='flight_book_user_id_c29baf_idx')],
            },
        ),
    ]
