# Generated by Django 5.2.7 on 2025-11-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0003_paxmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalregistration',
            name='cnic_back',
            field=models.ImageField(blank=True, help_text='CNIC Back Image', null=True, upload_to='universal/cnic/'),
        ),
        migrations.AlterField(
            model_name='universalregistration',
            name='cnic_front',
            field=models.ImageField(blank=True, help_text='CNIC Front Image', null=True, upload_to='universal/cnic/'),
        ),
        migrations.AlterField(
            model_name='universalregistration',
            name='visiting_card',
            field=models.ImageField(blank=True, help_text='Visiting Card Image', null=True, upload_to='universal/visiting_cards/'),
        ),
    ]
