# Generated by Django 4.2.1 on 2025-11-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0004_alter_universalregistration_cnic_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalregistration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=16),
        ),
    ]
