# Generated by Django 4.2.1 on 2026-01-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service charge name (e.g., 'Standard Service Charge', 'Premium Service Charge')", max_length=200)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', help_text='Type of charge: fixed amount or percentage', max_length=20)),
                ('charge_value', models.DecimalField(decimal_places=2, default=0, help_text='Charge value (amount for fixed, percentage for percentage type)', max_digits=12)),
                ('applied_on', models.CharField(choices=[('package', 'Package'), ('ticket', 'Ticket'), ('hotel', 'Hotel')], help_text='What this charge applies to: package, ticket, or hotel', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_charge_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceChargeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('package', 'Package'), ('ticket', 'Ticket'), ('hotel', 'Hotel')], help_text='Type of entity this charge is assigned to', max_length=20)),
                ('package_id', models.BigIntegerField(blank=True, null=True)),
                ('ticket_id', models.BigIntegerField(blank=True, null=True)),
                ('hotel_id', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_charge_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='service_charges.servicechargerule')),
            ],
            options={
                'db_table': 'service_charge_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_charge_rule'], name='service_cha_service_bb51b0_idx'), models.Index(fields=['assignment_type'], name='service_cha_assignm_79ed85_idx'), models.Index(fields=['package_id'], name='service_cha_package_3bc115_idx'), models.Index(fields=['ticket_id'], name='service_cha_ticket__306218_idx'), models.Index(fields=['hotel_id'], name='service_cha_hotel_i_8727c1_idx')],
            },
        ),
    ]
