# Generated by Django 4.2.1 on 2026-01-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_charges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quint_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge for Quint room', max_digits=12)),
                ('quad_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge for Quad room', max_digits=12)),
                ('triple_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge for Triple room', max_digits=12)),
                ('double_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge for Double room', max_digits=12)),
                ('sharing_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge for Sharing room', max_digits=12)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge for Other room type', max_digits=12)),
                ('hotel_ids', models.JSONField(default=list, help_text='List of hotel IDs this charge applies to')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_service_charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='servicechargerule',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='servicechargerule',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='servicechargerule',
            name='charge_value',
        ),
        migrations.AddField(
            model_name='servicechargerule',
            name='package_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Package charge value (fixed amount only)', max_digits=12),
        ),
        migrations.AddField(
            model_name='servicechargerule',
            name='ticket_charge_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', help_text='Type of charge for tickets: fixed amount or percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='servicechargerule',
            name='ticket_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ticket charge value (amount for fixed, percentage for percentage type)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicechargerule',
            name='name',
            field=models.CharField(help_text="Service charge group name (e.g., 'Standard Service Charge', 'Premium Service Charge')", max_length=200),
        ),
        migrations.DeleteModel(
            name='ServiceChargeAssignment',
        ),
        migrations.AddField(
            model_name='hotelservicecharge',
            name='service_charge_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_charges', to='service_charges.servicechargerule'),
        ),
    ]
