# Generated by Django 4.2.1 on 2025-11-01 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0070_add_public_booking_fields'),
        ('tickets', '0019_alter_hotels_organization'),
        ('packages', '0032_alter_umrahvisapricetwohotel_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], max_length=10)),
                ('flight_number', models.CharField(max_length=20)),
                ('flight_date', models.DateField()),
                ('flight_time', models.TimeField()),
                ('pickup_point', models.CharField(max_length=255)),
                ('drop_point', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('not_picked', 'Not Picked'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_transfers', to='booking.booking')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['flight_date', 'flight_time'],
            },
        ),
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('menu', models.TextField()),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('actual_service_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_services', to='booking.booking')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.city')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.hotels')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service_date', 'service_time'],
            },
        ),
        migrations.CreateModel(
            name='PaxMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('in_pakistan', 'In Pakistan'), ('entered_ksa', 'Entered KSA'), ('in_ksa', 'In KSA'), ('exited_ksa', 'Exited KSA')], default='in_pakistan', max_length=20)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('exit_verification', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('not_verified', 'Not Verified')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('flight_number_to_ksa', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_date_to_ksa', models.DateTimeField(blank=True, null=True)),
                ('flight_number_from_ksa', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_date_from_ksa', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_notified', models.BooleanField(default=False)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pax_movements', to='booking.booking')),
                ('current_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_pax', to='packages.city')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_movements', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_exits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='booking.booking')),
                ('drop_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_transports', to='packages.city')),
                ('pickup_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_transports', to='packages.city')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Ziyarat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('expected_return_time', models.TimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('guide_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guide_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarats', to='booking.booking')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.city')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='TransportPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('not_picked', 'Not Picked')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pax_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='pax_movements.paxmovement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingpersondetail')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='pax_movements.transport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodServicePax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='pax_movements.foodservice')),
                ('pax_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_services', to='pax_movements.paxmovement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirportTransferPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('not_picked', 'Not Picked')], default='waiting', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pax_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_transfers', to='pax_movements.paxmovement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingpersondetail')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='pax_movements.airporttransfer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZiyaratPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('not_picked', 'Not Picked')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pax_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarats', to='pax_movements.paxmovement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ziyarat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='pax_movements.ziyarat')),
            ],
            options={
                'unique_together': {('ziyarat', 'person')},
            },
        ),
        migrations.AddIndex(
            model_name='ziyarat',
            index=models.Index(fields=['scheduled_date'], name='pax_movemen_schedul_3028e1_idx'),
        ),
        migrations.AddIndex(
            model_name='ziyarat',
            index=models.Index(fields=['booking'], name='pax_movemen_booking_fcff07_idx'),
        ),
        migrations.AddIndex(
            model_name='ziyarat',
            index=models.Index(fields=['status'], name='pax_movemen_status_4cd762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportpax',
            unique_together={('transport', 'person')},
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['scheduled_date'], name='pax_movemen_schedul_f35752_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['booking'], name='pax_movemen_booking_5526f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['status'], name='pax_movemen_status_8a4f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='paxmovement',
            index=models.Index(fields=['pax_id'], name='pax_movemen_pax_id_a8053e_idx'),
        ),
        migrations.AddIndex(
            model_name='paxmovement',
            index=models.Index(fields=['booking'], name='pax_movemen_booking_a25f07_idx'),
        ),
        migrations.AddIndex(
            model_name='paxmovement',
            index=models.Index(fields=['status'], name='pax_movemen_status_42721d_idx'),
        ),
        migrations.AddIndex(
            model_name='paxmovement',
            index=models.Index(fields=['current_city'], name='pax_movemen_current_48db96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foodservicepax',
            unique_together={('food_service', 'person')},
        ),
        migrations.AddIndex(
            model_name='foodservice',
            index=models.Index(fields=['service_date'], name='pax_movemen_service_838729_idx'),
        ),
        migrations.AddIndex(
            model_name='foodservice',
            index=models.Index(fields=['booking'], name='pax_movemen_booking_55d4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='foodservice',
            index=models.Index(fields=['status'], name='pax_movemen_status_8fae12_idx'),
        ),
        migrations.AddIndex(
            model_name='foodservice',
            index=models.Index(fields=['meal_type'], name='pax_movemen_meal_ty_95c59f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='airporttransferpax',
            unique_together={('transfer', 'person')},
        ),
        migrations.AddIndex(
            model_name='airporttransfer',
            index=models.Index(fields=['flight_date'], name='pax_movemen_flight__e4b9db_idx'),
        ),
        migrations.AddIndex(
            model_name='airporttransfer',
            index=models.Index(fields=['booking'], name='pax_movemen_booking_a9cb79_idx'),
        ),
        migrations.AddIndex(
            model_name='airporttransfer',
            index=models.Index(fields=['status'], name='pax_movemen_status_2f28c2_idx'),
        ),
    ]
