# Generated by Django 4.2.1 on 2025-11-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_hotelrooms_floor'),
        ('packages', '0031_add_public_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umrahvisapricetwohotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.hotels'),
        ),
    ]
