# Generated by Django 4.2.1 on 2025-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0035_alter_customumrahpackagehoteldetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customumrahpackagetransportdetails',
            options={'verbose_name': 'Custom Transport Detail', 'verbose_name_plural': 'Custom Transport Details'},
        ),
        migrations.AlterModelOptions(
            name='umrahpackagetransportdetails',
            options={'verbose_name': 'Transport Detail', 'verbose_name_plural': 'Transport Details'},
        ),
        migrations.AddField(
            model_name='customumrahpackagetransportdetails',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('private', 'Private Transport'), ('shared', 'Shared Transport'), ('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('airport_transfer', 'Airport Transfer'), ('intercity', 'Intercity'), ('local', 'Local Transport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customumrahpackagetransportdetails',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan Car'), ('suv', 'SUV'), ('van', 'Van'), ('minibus', 'Mini Bus'), ('coaster', 'Coaster'), ('bus', 'Large Bus'), ('luxury_bus', 'Luxury Bus'), ('hiace', 'Hiace')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='umrahpackagetransportdetails',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('private', 'Private Transport'), ('shared', 'Shared Transport'), ('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('airport_transfer', 'Airport Transfer'), ('intercity', 'Intercity'), ('local', 'Local Transport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='umrahpackagetransportdetails',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan Car'), ('suv', 'SUV'), ('van', 'Van'), ('minibus', 'Mini Bus'), ('coaster', 'Coaster'), ('bus', 'Large Bus'), ('luxury_bus', 'Luxury Bus'), ('hiace', 'Hiace')], max_length=50, null=True),
        ),
    ]
