# Generated by Django 4.2.1 on 2025-11-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0038_add_top_level_purchase_selling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umrahpackage',
            old_name='madinah_ziyarat_purchase_price',
            new_name='madinah_ziarat_purchase_price',
        ),
    ]
