# Generated by Django 5.2.7 on 2025-11-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_hotels_google_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='inventory_owner_organization_id',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='category',
            field=models.CharField(choices=[('economy', 'Economy'), ('budget', 'Budget'), ('standard', 'Standard'), ('deluxe', 'Deluxe'), ('luxury', 'Luxury'), ('5_star', '5 Star'), ('4_star', '4 Star'), ('3_star', '3 Star'), ('2_star', '2 Star')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('maintenance', 'Maintenance')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='video',
            field=models.FileField(blank=True, help_text='Upload hotel video', null=True, upload_to='hotel_videos/'),
        ),
    ]
