# Generated by Django 5.2.7 on 2025-11-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_hotels_inventory_owner_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelcontactdetails',
            options={'verbose_name': 'Hotel Contact Detail', 'verbose_name_plural': 'Hotel Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='hotelphoto',
            options={'verbose_name': 'Hotel Photo', 'verbose_name_plural': 'Hotel Photos'},
        ),
        migrations.AlterModelOptions(
            name='hotelprices',
            options={'verbose_name': 'Hotel Price', 'verbose_name_plural': 'Hotel Prices'},
        ),
        migrations.AlterModelOptions(
            name='hotelrooms',
            options={'verbose_name': 'Hotel Room', 'verbose_name_plural': 'Hotel Rooms'},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ['name'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='roomdetails',
            options={'verbose_name': 'Room Detail', 'verbose_name_plural': 'Room Details'},
        ),
    ]
