# Generated by Django 4.2.1 on 2025-11-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_hotelcontactdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprices',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('quint', 'Quint'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('executive', 'Executive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelrooms',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('quint', 'Quint'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('executive', 'Executive')], max_length=50),
        ),
    ]
