# Generated by Django 4.2.1 on 2025-11-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0032_alter_umrahvisapricetwohotel_hotel'),
        ('tickets', '0017_alter_hotelrooms_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='available_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='available_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='packages.city'),
        ),
    ]
