# Generated by Django 4.2.1 on 2025-11-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_agency_agency_id_remove_branch_branch_id_and_more'),
        ('tickets', '0018_alter_hotels_available_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='organization.organization'),
        ),
    ]
