# Generated by Django 4.2.1 on 2025-11-01 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0032_alter_umrahvisapricetwohotel_hotel'),
        ('organization', '0016_alter_employee_position_alter_employee_user'),
        ('tickets', '0019_alter_hotels_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-departure_date', 'departure_time'], 'verbose_name': 'Flight Ticket', 'verbose_name_plural': 'Flight Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='adult_fare',
            field=models.FloatField(default=0, help_text='Adult fare price'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='Arrival date', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Arrival time', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='baggage_pieces',
            field=models.IntegerField(default=0, help_text='Number of baggage pieces allowed'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='baggage_weight',
            field=models.FloatField(default=0, help_text='Baggage allowance in KG'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='child_fare',
            field=models.FloatField(default=0, help_text='Child fare price'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Departure date', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Departure time', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Arrival city', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_tickets', to='packages.city'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_number',
            field=models.CharField(blank=True, help_text='Flight number (e.g., EK-502)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='infant_fare',
            field=models.FloatField(default=0, help_text='Infant fare price'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='Departure city', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_tickets', to='packages.city'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_rule',
            field=models.CharField(choices=[('non_refundable', 'Non-Refundable'), ('refundable', 'Refundable'), ('partially_refundable', 'Partially Refundable')], default='non_refundable', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first_class', 'First Class')], default='economy', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_tickets',
            field=models.IntegerField(default=0, help_text='Total booked seats'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='confirmed_tickets',
            field=models.IntegerField(default=0, help_text='Total confirmed seats'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='left_seats',
            field=models.IntegerField(default=0, help_text='Remaining seats'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner_organization_id',
            field=models.IntegerField(blank=True, help_text='Organization that owns this inventory', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(help_text='Passenger Name Record', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reselling_allowed',
            field=models.BooleanField(default=False, help_text='Allow reselling by other agencies'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_seats',
            field=models.IntegerField(default=0, help_text='Total seats available'),
        ),
    ]
