# Generated by Django 4.2.1 on 2025-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_ticket_options_ticket_adult_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprices',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hotelprices',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
