# Generated by Django 4.2.1 on 2025-11-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_add_ticket_purchase_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprices',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='hotelprices',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Unique ticket number', max_length=20, null=True, unique=True),
        ),
    ]
