# Generated by Django 4.2.1 on 2025-11-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_hotelprices_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(blank=True, default='N/A', help_text='Passenger Name Record', max_length=100),
        ),
    ]
