# Generated by Django 5.2.7 on 2025-11-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_ticket_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='walking_time_minutes',
            field=models.IntegerField(blank=True, help_text='Walking time in minutes from reference point', null=True),
        ),
    ]
