# Generated by Django 4.2.1 on 2025-11-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_add_hotelprices_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprices',
            name='profit',
        ),
    ]
