# Generated by Django 4.2.1 on 2025-11-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_add_hotelprices_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprices',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='walking_time_minutes',
        ),
        migrations.AddField(
            model_name='tickettripdetails',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
