# Generated by Django A.I. assistant
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_remove_hotelprices_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_categories', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Hotel Category',
                'verbose_name_plural': 'Hotel Categories',
                'ordering': ['name'],
            },
        ),
    ]
