# Generated by Django 4.2.1 on 2025-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_add_hotels_walking_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='walking_time',
            field=models.FloatField(default=0, help_text='Walking time in minutes (user-entered)'),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
