# Generated by Django 4.2.1 on 2025-11-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_hotelprices_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprices',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('sharing', 'Sharing'), ('room', 'Room'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('quint', 'Quint'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('executive', 'Executive')], max_length=50),
        ),
    ]
