# Generated by Django 4.2.1 on 2025-12-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_add_resellrequest_items'),
        ('tickets', '0033_alter_hotelprices_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_types', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Bed Type',
                'verbose_name_plural': 'Bed Types',
                'ordering': ['name'],
                'unique_together': {('name', 'organization'), ('slug', 'organization')},
            },
        ),
    ]
