# Generated by Django 4.2.1 on 2025-12-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_add_resellrequest_items'),
        ('tickets', '0034_bedtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bedtype',
            unique_together={('slug', 'organization')},
        ),
        migrations.AddField(
            model_name='bedtype',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Default capacity for this bed type'),
        ),
    ]
