# Generated by Django 4.2.1 on 2025-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_alter_bedtype_unique_together_bedtype_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
