# Generated by Django 4.2.1 on 2025-12-05 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_alter_bedtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Default capacity for this bed type (max 10)', validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1'), django.core.validators.MaxValueValidator(10, message='Capacity cannot exceed 10 beds')]),
        ),
    ]
