# Generated by Django 4.2.1 on 2025-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_alter_bedtype_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprices',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('sharing', 'Sharing'), ('room', 'Room'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('quint', 'Quint'), ('6-bed', '6 Bed'), ('7-bed', '7 Bed'), ('8-bed', '8 Bed'), ('9-bed', '9 Bed'), ('10-bed', '10 Bed'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('executive', 'Executive')], max_length=50),
        ),
    ]
