# Generated by Django 4.2.1 on 2025-12-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_hotelrooms_status_roomdetails_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(choices=[('ground', 'Ground Floor'), ('0', 'Ground Floor'), ('1', '1st Floor'), ('2', '2nd Floor'), ('3', '3rd Floor'), ('4', '4th Floor'), ('5', '5th Floor'), ('6', '6th Floor'), ('7', '7th Floor'), ('8', '8th Floor'), ('9', '9th Floor'), ('10', '10th Floor'), ('basement', 'Basement')], max_length=50)),
                ('floor_title', models.CharField(blank=True, max_length=100, null=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='floor_maps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='tickets.hotels')),
            ],
            options={
                'verbose_name': 'Hotel Floor',
                'verbose_name_plural': 'Hotel Floors',
                'ordering': ['hotel', 'floor_no'],
                'unique_together': {('hotel', 'floor_no')},
            },
        ),
    ]
