# Generated by Django 4.2.1 on 2025-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_hotelfloor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelfloor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
