# Generated by Django 4.2.1 on 2025-12-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_alter_hotelprices_room_type'),
        ('tickets', '0040_hotelfloor_is_active'),
    ]

    operations = [
    ]
