# Generated by Django 4.2.1 on 2026-01-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_merge_20251228_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_last_name', models.CharField(max_length=100)),
                ('gender_type', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Child', 'Child')], default='Mr', max_length=10)),
                ('document_type', models.CharField(choices=[('CNIC', 'CNIC'), ('Passport', 'Passport')], default='CNIC', max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.roomdetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.hotels')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.hotelrooms')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
