# Generated by Django 4.2.1 on 2026-01-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0042_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='agent_name',
            field=models.CharField(blank=True, help_text='Agent username or email', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='agent_organization',
            field=models.CharField(blank=True, help_text='Agent organization name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booked_by_agent',
            field=models.ForeignKey(blank=True, help_text='Agent who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
