# Generated by Django 4.2.1 on 2026-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_hotelbooking_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='List of historical changes to ticket timing'),
        ),
    ]
