# Generated by Django 4.2.1 on 2025-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_remove_commissionearning_comm_e_booking_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrule',
            name='commission',
            field=models.JSONField(blank=True, default=dict, help_text='Basic commission values: {group_ticket_commission_amount, umrah_package_commission_amount}', null=True),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='hotel_night_commission',
            field=models.JSONField(blank=True, default=list, help_text='Array of hotel commission configs with room type rates and hotel assignments', null=True),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='name',
            field=models.CharField(default='', help_text="Commission group name (e.g., 'Low Level', 'High Level')", max_length=200),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='applied_on_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='commission_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='receiver_type',
            field=models.CharField(default='branch', help_text="Who receives: 'branch', 'area_agent', 'employee'", max_length=50),
        ),
    ]
