# Generated by Django 4.2.1 on 2025-11-01 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_ticket_options_ticket_adult_fare_and_more'),
        ('booking', '0071_alter_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='Select ticket for this passenger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_bookings', to='tickets.ticket'),
        ),
    ]
