# Generated by Django 4.2.1 on 2025-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0076_remove_payment_agent_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ledger_entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('direct', 'Direct')], default='booking', max_length=20),
        ),
    ]
